import { Lusitana, Inter } from "next/font/google";
import styles from "./globals.module.css";
import Link from "next/link";

export const lusitana = Lusitana({ subsets: ["latin"], weight: "400", display: "swap"});
export const inter = Inter({subsets: ["latin"], weight: "900", display: "swap"} );

export const metadata = {
  title: "Alejo Borracci",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={lusitana.className}>
      <body className={styles.body}>
        <div className={styles.boxnav}>
          <div className={styles.nav}>
            <Link href={"/home"}>
              <button>Home</button>
            </Link>
            <Link href={"/home/about"}>
              <button>About</button>
            </Link>
            <Link href={"/home/profile"}>
              <button>My profile</button>
            </Link>
            <Link href={"/home/chanells"}>
              <button>Channels</button>
            </Link>
          </div>
        </div>

        <div className={styles.boxpage}>{children}</div>
      </body>
    </html>
  );
}
