import { Inter } from "next/font/google";

import styles from "./globals.module.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Alejo Borracci",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={styles.html}>
      <body className={styles.body}>  

        <div className={styles.boxnav}>
          <div className={styles.nav}>
            <button>Home</button>
            <button>About</button>
            <button>My profile</button>
            <button>Channels</button>
          </div>
        </div>

        <div className={styles.boxpage}>
          {children}
        </div>
      </body>
    </html>
  );
}
