import { Inter } from "next/font/google";

import styles from "./globals.module.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Alejo Borracci",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={styles.html}>
      <body className={inter.className}>
        {children}
        <p>Footer del layout</p>
        </body>
    </html>
  );
}
